@startuml Bank Sequence Diagram
actor User
participant "Login Page" as Login
participant "Register Page" as Register
participant "Bank System" as System
participant "Text File" as TextFile
participant "Home Screen" as Home
participant "Transaction Tab" as Transaction
participant "Account Tab" as Account

== Login or Register ==
' User log in with credentials
alt Login
    User -> Login : Enter username/password
    Login -> System : Authenticate credentials
alt Login Success 
    System -> Login : Login successful
'If user gives incorrect credentials then display an error
else Login Error 
    System -> Login: Login unsuccessful
    Login -> User : ERROR: Incorrect Username or Password
    User -> Login: Re-enter username/password
end
' If the user does not have an account then they must register
else Register
    User -> Register : Enter username, password, balances, pin
    Register -> System : Create account
    System -> TextFile : Write account info to file
    TextFile --> System : Confirm write
    System -> Register : Success
    Register -> User: Account Created Successfully!
    User -> Login: Log in with new account
end
    ' Show welcome screen after user logs in
    Login -> Home : Show Welcome screen

== View Balances ==
    User -> Home : View balances
    Home -> System : Fetch checkings/savings
    System -> Home : Return balances
    Home -> User : Show balances

== Deposit ==
    User -> Transaction : Select Deposit
    Transaction -> User : Select account and enter amount
' Savings Scenario
alt Savings 
    User -> Transaction : Selects Savings and enters amount
    Transaction -> System : Process deposit
    System -> Transaction : Deposit accepted
    System -> System : Update Savings account balance
    Transaction -> User : Deposit Successful
' Checkings Scenario
else Checkings
    User -> Transaction : Selects Checkings and enters amount
    Transaction -> System : Process deposit
    System -> Transaction : Deposit accepted
    System -> System : Update Checkings account balance
    Transaction -> User : Deposit Successful
end
    ' Update text file balance
    System -> TextFile : Update Text File
    TextFile --> System : Confirm
    System -> Transaction : Success
    Transaction -> Home : Back to home

== Withdraw ==
    User -> Transaction : Select Withdraw
    Transaction -> User : Select account, enter amount
' Savings Scenario
alt Savings 
    User -> Transaction : Selects Savings and enters amount
    Transaction -> System : Process withdrawal
' If the withdraw is successful
alt Successful Savings Withdraw
    System -> Transaction : Deposit accepted
    System -> System : Update Savings account balance
    Transaction -> User : Deposit Successful
    System -> TextFile : Update Text File
    TextFile --> System : Confirm
    System -> Transaction : Success
    Transaction -> Home : Back to home
' Savings Withdraw Error
else Savings Withdraw Error 
    System -> Transaction : ERROR insufficient funds
    Transaction -> User : Insufficient funds for this withdrawal
end
' Checkings Scenario
else Checkings
' If the withdraw is successful
alt Successful Checkings Withdraw
    User -> Transaction : Selects Checkings and enters amount
    Transaction -> System : Process withdrawal
    System -> Transaction : Deposit accepted
    System -> System : Update Checkings account balance
    Transaction -> User : Deposit Successful
    System -> TextFile : Update Text File
    TextFile --> System : Confirm
    System -> Transaction : Success
    Transaction -> Home : Back to home
' Checkings Withdraw Error
else Checkings Withdraw Error
    System -> Transaction : ERROR insufficient funds
    Transaction -> User : Insufficient funds for this withdrawal
end
end

== Send/Request Money ==
    User -> Transaction : Select Send/Request
    Transaction -> User : Enter user, account type, amount
    Transaction -> System : Connect to user
    System -> System : Verify connection
    Transaction -> User : Enter PIN / Accept request
    Transaction -> System : Process send/request
    System -> TextFile : Log transaction
    TextFile --> System : Confirm
    System -> Transaction : Success
    Transaction -> Home : Back to home

== Transfer Between Accounts ==
    User -> Account : Select Transfer
    Account -> User : Enter Amount
    User -> Account : User enters amount
    Account -> User : Select Account to get transfer
    User -> Account : Selects account and presses transfer
    Account -> System : Process Transfer
' If transfer is successful
alt Successful Transfer 
    System -> Account : Transfer accepted
    Account -> User : Successfully transfered to account
     System -> TextFile : Update Text File
    TextFile --> System : Confirm
    System -> Account : Success
    Account -> Home : Back to home
' If transfer is unsuccessful
else Unsuccessful Transfer
    System -> Account : ERROR insufficient balance in other account
    Account -> User : ERROR: Insufficent account balance
end

== Show Previous Transactions ==
User -> Account : View previous transactions
Account -> User : Show previous logs
@enduml
